trainArgs:
  learning_rate: 1.0e-4
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  max_steps: 1000


  learning_rate = 1e-4,
    per_device_train_batch_size = 32,
    per_device_eval_batch_size = 32,
    max_steps = 1,
    logging_steps = 1,
    weight_decay = 0.01,
    eval_strategy = 'steps',
    save_strategy = 'steps',
    eval_steps = 1,
    save_steps = 1,
    warmup_steps=1,
    load_best_model_at_end = Tru